### ISSUE TITLE
Does this adapter work with Sails version 0.11?

### ISSUE THREAD

**Issue by jasonw401** [atiertant/sails-oracle#5]
I have tried this adapter on sails version 0.11. The sails can be lift,  but I got the following error when I try to access an API URL: http://[host]:1337/user
# 

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

/root/test/node_modules/sails-oracledb/index.js:1386
            cnx.execute(query, data, function(err, result) {
                ^
TypeError: Cannot call method 'execute' of null
    at /root/test/node_modules/sails-oracledb/index.js:1386:17
    at /root/test/node_modules/sails-oracledb/node_modules/generic-pool/lib/generic-pool.js:274:11
    at /root/test/node_modules/sails-oracledb/index.js:99:36
# 

connections.js

module.exports.connections = {

  oracleServer: {
    adapter: 'sails-oracledb',
    tns: '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.0.109)(PORT 
= 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = ex)))',
    user: 'user',
    password: 'pass'
  }
}

model.js

module.exports.connections = {
 connection: 'oracleServer'
}

I am using Oracle Express Edition. The database connection has been tested by SQL PLus, but I am not sure how to verify it by sails.

Thanks.

**Comment by jasonw401** [comment]
I found a problem in my connection string, so I get pass the error above, but got a table not found error as below:

debug: --------------------------------------------------------
debug: :: Thu Feb 26 2015 12:42:55 GMT+1100 (EST)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: ORA-00942: table or view does not exist

Details:  Error: ORA-00942: table or view does not exist

I have created the table on database. Could someone suggest how to map the table and the model?

I used the following table:

SQL> desc dept;
 Name                      Null?    Type

---

 DEPTNO                    NOT NULL NUMBER(2)
 DNAME                          VARCHAR2(14)
 LOC                            VARCHAR2(13)

The model Dept.js is:

module.exports = {
tableName : 'myuser.dept',
  attributes: {
DEPTNO : {type : 'string'},
DNAME: {type : 'string'},
LOC: {type : 'string'}
  }
};

Thanks.
